// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddDiscoveryReducer from "../add_discovery_reducer";
import ApplyProposalReducer from "../apply_proposal_reducer";
import LogEventReducer from "../log_event_reducer";
import RecordDailyMetricsReducer from "../record_daily_metrics_reducer";
import RecordHealingReducer from "../record_healing_reducer";
import ResetLayoutReducer from "../reset_layout_reducer";
import SaveWidgetLayoutReducer from "../save_widget_layout_reducer";
import SubmitProposalReducer from "../submit_proposal_reducer";
import TriggerRebootReducer from "../trigger_reboot_reducer";
import UpdateGatewaySnapshotReducer from "../update_gateway_snapshot_reducer";
import UpdateHealthReducer from "../update_health_reducer";

export type AddDiscoveryParams = __Infer<typeof AddDiscoveryReducer>;
export type ApplyProposalParams = __Infer<typeof ApplyProposalReducer>;
export type LogEventParams = __Infer<typeof LogEventReducer>;
export type RecordDailyMetricsParams = __Infer<typeof RecordDailyMetricsReducer>;
export type RecordHealingParams = __Infer<typeof RecordHealingReducer>;
export type ResetLayoutParams = __Infer<typeof ResetLayoutReducer>;
export type SaveWidgetLayoutParams = __Infer<typeof SaveWidgetLayoutReducer>;
export type SubmitProposalParams = __Infer<typeof SubmitProposalReducer>;
export type TriggerRebootParams = __Infer<typeof TriggerRebootReducer>;
export type UpdateGatewaySnapshotParams = __Infer<typeof UpdateGatewaySnapshotReducer>;
export type UpdateHealthParams = __Infer<typeof UpdateHealthReducer>;

