// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64(),
  timestamp: __t.u64(),
  category: __t.string(),
  toolAffected: __t.string().name("tool_affected"),
  description: __t.string(),
  diff: __t.string(),
  status: __t.string(),
  evalScoreBefore: __t.f64().name("eval_score_before"),
  evalScoreAfter: __t.f64().name("eval_score_after"),
  appliedAt: __t.u64().name("applied_at"),
});
