// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  date: __t.string(),
  totalToolCalls: __t.u64().name("total_tool_calls"),
  successfulCalls: __t.u64().name("successful_calls"),
  failedCalls: __t.u64().name("failed_calls"),
  avgLatencyMs: __t.f64().name("avg_latency_ms"),
  promptfooScore: __t.f64().name("promptfoo_score"),
  topFailedTool: __t.string().name("top_failed_tool"),
});
