// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  date: __t.string(),
  totalToolCalls: __t.u64(),
  successfulCalls: __t.u64(),
  failedCalls: __t.u64(),
  avgLatencyMs: __t.f64(),
  promptfooScore: __t.f64(),
  topFailedTool: __t.string(),
};
