// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  widgetId: __t.string(),
  gridX: __t.u32(),
  gridY: __t.u32(),
  gridW: __t.u32(),
  gridH: __t.u32(),
  visible: __t.bool(),
  config: __t.string(),
};
