// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ArchitectProposal = __t.object("ArchitectProposal", {
  id: __t.u64(),
  timestamp: __t.u64(),
  category: __t.string(),
  toolAffected: __t.string(),
  description: __t.string(),
  diff: __t.string(),
  status: __t.string(),
  evalScoreBefore: __t.f64(),
  evalScoreAfter: __t.f64(),
  appliedAt: __t.u64(),
});
export type ArchitectProposal = __Infer<typeof ArchitectProposal>;

export const DailyMetrics = __t.object("DailyMetrics", {
  date: __t.string(),
  totalToolCalls: __t.u64(),
  successfulCalls: __t.u64(),
  failedCalls: __t.u64(),
  avgLatencyMs: __t.f64(),
  promptfooScore: __t.f64(),
  topFailedTool: __t.string(),
});
export type DailyMetrics = __Infer<typeof DailyMetrics>;

export const DiscoveryFeed = __t.object("DiscoveryFeed", {
  title: __t.string(),
  category: __t.string(),
  content: __t.string(),
  timestamp: __t.u64(),
});
export type DiscoveryFeed = __Infer<typeof DiscoveryFeed>;

export const GatewaySnapshot = __t.object("GatewaySnapshot", {
  source: __t.string(),
  data: __t.string(),
  fetchedAt: __t.u64(),
  status: __t.string(),
});
export type GatewaySnapshot = __Infer<typeof GatewaySnapshot>;

export const HealingAction = __t.object("HealingAction", {
  id: __t.u64(),
  eventId: __t.u64(),
  timestamp: __t.u64(),
  service: __t.string(),
  action: __t.string(),
  result: __t.string(),
  details: __t.string(),
});
export type HealingAction = __Infer<typeof HealingAction>;

export const ServiceHealth = __t.object("ServiceHealth", {
  serviceName: __t.string(),
  status: __t.string(),
  lastSeen: __t.u64(),
});
export type ServiceHealth = __Infer<typeof ServiceHealth>;

export const SystemEvent = __t.object("SystemEvent", {
  id: __t.u64(),
  timestamp: __t.u64(),
  severity: __t.string(),
  service: __t.string(),
  payload: __t.string(),
});
export type SystemEvent = __Infer<typeof SystemEvent>;

export const WidgetLayout = __t.object("WidgetLayout", {
  widgetId: __t.string(),
  gridX: __t.u32(),
  gridY: __t.u32(),
  gridW: __t.u32(),
  gridH: __t.u32(),
  visible: __t.bool(),
  config: __t.string(),
});
export type WidgetLayout = __Infer<typeof WidgetLayout>;

