// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  widgetId: __t.string().name("widget_id"),
  gridX: __t.u32().name("grid_x"),
  gridY: __t.u32().name("grid_y"),
  gridW: __t.u32().name("grid_w"),
  gridH: __t.u32().name("grid_h"),
  visible: __t.bool(),
  config: __t.string(),
});
